services:
  ibnt.server:
    container_name: ibnt-api
    build:
        context: .
        dockerfile: Ibnt.Server/Dockerfile
    restart: on-failure

    ports:
        - "8080:8080"
        - "8081:8081"
volumes:
  app-data:  